### ISSUE TITLE
[UE5.4] Build errors

### ISSUE THREAD

**Issue by njahs** [rengeln/StyledWidgets#1]
Hello,

I wanted to try out the last changes for Unreal Engine 5.4 but I'm not able to build a project using the latest plugin version. Unfortunatly the errors are kinda generic and my IDE doesn't help me here. There are no errors in cpp/header files, but the project doesn't build. Are there any other requirements / settings that have to be enabled in the project?

These are the errors I get:
(I created a fresh unreal engine 5.4 C++ project)

> ------ Building 5 action(s) started ------
[1/5] Compile [x64] StyledActivatableWidget.cpp
[2/5] Compile [x64] Module.StyledWidgets.cpp
[3/5] Link [x64] UnrealEditor-StyledWidgets.lib
   Bibliothek "S:\Unreal_Projects\Unreal54\Plugins\StyledWidgets\Intermediate\Build\Win64\x64\UnrealEditor\Development\StyledWidgets\UnrealEditor-StyledWidgets.lib" und Objekt "S:\Unreal_Projects\Unreal54\Plugins\StyledWidgets\Intermediate\Build\Win64\x64\UnrealEditor\Development\StyledWidgets\UnrealEditor-StyledWidgets.exp" werden erstellt.
[4/5] Link [x64] UnrealEditor-StyledWidgets.dll
   Bibliothek "S:\Unreal_Projects\Unreal54\Plugins\StyledWidgets\Intermediate\Build\Win64\x64\UnrealEditor\Development\StyledWidgets\UnrealEditor-StyledWidgets.sup.lib" und Objekt "S:\Unreal_Projects\Unreal54\Plugins\StyledWidgets\Intermediate\Build\Win64\x64\UnrealEditor\Development\StyledWidgets\UnrealEditor-StyledWidgets.sup.exp" werden erstellt.
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: void __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleStyleTagsChanged(void)" (?HandleStyleTagsChanged@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAAXXZ)" in Funktion ""public: virtual void __cdecl UStyledActivatableWidget::AddStyleTag(class FName const &)" (?AddStyleTag@UStyledActivatableWidget@@UEAAXAEBVFName@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: void __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::RebuildStyle(void)" (?RebuildStyle@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAAXXZ)" in Funktion ""protected: virtual void __cdecl UStyledActivatableWidget::PostEditChangeProperty(struct FPropertyChangedEvent &)" (?PostEditChangeProperty@UStyledActivatableWidget@@MEAAXAEAUFPropertyChangedEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: void __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleMouseEnter(struct FPointerEvent const &)" (?HandleMouseEnter@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAAXAEBUFPointerEvent@@@Z)" in Funktion ""protected: virtual void __cdecl UStyledActivatableWidget::NativeOnMouseEnter(struct FGeometry const &,struct FPointerEvent const &)" (?NativeOnMouseEnter@UStyledActivatableWidget@@MEAAXAEBUFGeometry@@AEBUFPointerEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: void __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleMouseLeave(struct FPointerEvent const &)" (?HandleMouseLeave@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAAXAEBUFPointerEvent@@@Z)" in Funktion ""protected: virtual void __cdecl UStyledActivatableWidget::NativeOnMouseLeave(struct FPointerEvent const &)" (?NativeOnMouseLeave@UStyledActivatableWidget@@MEAAXAEBUFPointerEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: class FReply __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleFocusReceived(struct FFocusEvent const &)" (?HandleFocusReceived@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAA?AVFReply@@AEBUFFocusEvent@@@Z)" in Funktion ""protected: virtual class FReply __cdecl UStyledActivatableWidget::NativeOnFocusReceived(struct FGeometry const &,struct FFocusEvent const &)" (?NativeOnFocusReceived@UStyledActivatableWidget@@MEAA?AVFReply@@AEBUFGeometry@@AEBUFFocusEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: void __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleFocusLost(struct FFocusEvent const &)" (?HandleFocusLost@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAAXAEBUFFocusEvent@@@Z)" in Funktion ""protected: virtual void __cdecl UStyledActivatableWidget::NativeOnFocusLost(struct FFocusEvent const &)" (?NativeOnFocusLost@UStyledActivatableWidget@@MEAAXAEBUFFocusEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: class FReply __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleMouseButtonDown(struct FPointerEvent const &)" (?HandleMouseButtonDown@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAA?AVFReply@@AEBUFPointerEvent@@@Z)" in Funktion ""protected: virtual class FReply __cdecl UStyledActivatableWidget::NativeOnMouseButtonDown(struct FGeometry const &,struct FPointerEvent const &)" (?NativeOnMouseButtonDown@UStyledActivatableWidget@@MEAA?AVFReply@@AEBUFGeometry@@AEBUFPointerEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: class FReply __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleMouseButtonUp(struct FPointerEvent const &)" (?HandleMouseButtonUp@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAA?AVFReply@@AEBUFPointerEvent@@@Z)" in Funktion ""protected: virtual class FReply __cdecl UStyledActivatableWidget::NativeOnMouseButtonUp(struct FGeometry const &,struct FPointerEvent const &)" (?NativeOnMouseButtonUp@UStyledActivatableWidget@@MEAA?AVFReply@@AEBUFGeometry@@AEBUFPointerEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: class FReply __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleKeyDown(struct FKeyEvent const &)" (?HandleKeyDown@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAA?AVFReply@@AEBUFKeyEvent@@@Z)" in Funktion ""protected: virtual class FReply __cdecl UStyledActivatableWidget::NativeOnKeyDown(struct FGeometry const &,struct FKeyEvent const &)" (?NativeOnKeyDown@UStyledActivatableWidget@@MEAA?AVFReply@@AEBUFGeometry@@AEBUFKeyEvent@@@Z)".
11>StyledActivatableWidget.cpp.obj: Error LNK2019 : Verweis auf nicht aufgelöstes externes Symbol ""protected: class FReply __cdecl TStyledWidgetBase<class UStyledActivatableWidget>::HandleKeyUp(struct FKeyEvent const &)" (?HandleKeyUp@?$TStyledWidgetBase@VUStyledActivatableWidget@@@@IEAA?AVFReply@@AEBUFKeyEvent@@@Z)" in Funktion ""protected: virtual class FReply __cdecl UStyledActivatableWidget::NativeOnKeyUp(struct FGeometry const &,struct FKeyEvent const &)" (?NativeOnKeyUp@UStyledActivatableWidget@@MEAA?AVFReply@@AEBUFGeometry@@AEBUFKeyEvent@@@Z)".
11>UnrealEditor-StyledWidgets.dll: Error LNK1120 : 10 nicht aufgelöste Externe
Total time in Parallel executor: 1.80 seconds

Thanks :)

**Comment by rengeln** [comment]
Hi Marco, I just checked in a fix for this particular build error. Let me know if it's still broken for you.

**Comment by njahs** [comment]
The build error is gone - time to explore :)
